In [53]:
from pretrainedModel import pretrainedModel

In [54]:
from tensorflow import keras
from PIL import Image
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()
image = Image.fromarray(x_train[0]).convert('RGB')

In [55]:
model = pretrainedModel()
model(image).shape

torch.Size([2048])

In [56]:
image

In [57]:
y_train[0]

5

In [58]:
import torch.nn as nn
import torch

n_hash = 32

model2 = nn.Sequential(nn.Linear( 2048 , 128 ),
                     nn.ReLU(),
                     nn.Linear( 128 ,64),
                     nn.ReLU(),
                     nn.Linear(64, n_hash ),
                     nn.Sigmoid()
                     )

In [59]:
model2(model(image))

tensor([0.4673, 0.5045, 0.5344, 0.5262, 0.4840, 0.4839, 0.4896, 0.5186, 0.5215,
        0.4847, 0.5193, 0.4905, 0.5079, 0.5002, 0.4955, 0.5085, 0.4890, 0.4833,
        0.4876, 0.4926, 0.4990, 0.4897, 0.4726, 0.5146, 0.4843, 0.4990, 0.4974,
        0.4808, 0.5122, 0.5399, 0.5172, 0.4935], grad_fn=<SigmoidBackward0>)

In [60]:
for i in range(len(y_train)):
    if y_train[i] == 5:
        print(i)
    
    if i == 50: break


0
11
35
47


In [61]:
p = Image.fromarray(x_train[11]).convert('RGB')
p

In [62]:
n = Image.fromarray(x_train[2]).convert('RGB')
n

In [63]:
anchor

tensor([0.5012, 0.4754, 0.5356, 0.5246, 0.4974, 0.4821, 0.4993, 0.4790, 0.5156,
        0.5093, 0.5003, 0.5230, 0.4887, 0.5042, 0.4769, 0.5275, 0.4732, 0.4994,
        0.5045, 0.5397, 0.4781, 0.4988, 0.5122, 0.4865, 0.4813, 0.4959, 0.4778,
        0.5283, 0.4705, 0.5014, 0.5049, 0.4904], grad_fn=<SigmoidBackward0>)

In [64]:
pExam

tensor([0.4994, 0.4757, 0.5338, 0.5262, 0.4970, 0.4819, 0.4987, 0.4775, 0.5166,
        0.5127, 0.5004, 0.5209, 0.4863, 0.5065, 0.4804, 0.5270, 0.4757, 0.5003,
        0.5031, 0.5374, 0.4737, 0.4983, 0.5097, 0.4839, 0.4805, 0.4987, 0.4773,
        0.5272, 0.4784, 0.4974, 0.5034, 0.4905], grad_fn=<SigmoidBackward0>)

In [65]:
nExam

tensor([0.5019, 0.4749, 0.5347, 0.5214, 0.4992, 0.4819, 0.4958, 0.4798, 0.5133,
        0.5090, 0.5018, 0.5253, 0.4895, 0.5074, 0.4778, 0.5248, 0.4751, 0.4979,
        0.5063, 0.5396, 0.4773, 0.4983, 0.5106, 0.4851, 0.4821, 0.4964, 0.4777,
        0.5261, 0.4736, 0.4972, 0.5017, 0.4880], grad_fn=<SigmoidBackward0>)

In [66]:
import torch.optim as optim

triplet_loss = nn.TripletMarginLoss(margin=1.0, p=2, eps=1e-7)
optimizer = optim.SGD(model2.parameters(),lr=0.7, momentum=0.9)

In [72]:
anchor = model2(model(image))
pExam =  model2(model(p))
nExam =  model2(model(n))

optimizer.zero_grad()

loss = triplet_loss(
            torch.stack([anchor,anchor]), 
            torch.stack([pExam,pExam]), 
            torch.stack([nExam,nExam]))

loss.backward()
loss

tensor(0.9961, grad_fn=<MeanBackward0>)

In [68]:
torch.stack([anchor,anchor])

tensor([[0.4673, 0.5045, 0.5344, 0.5262, 0.4840, 0.4839, 0.4896, 0.5186, 0.5215,
         0.4847, 0.5193, 0.4905, 0.5079, 0.5002, 0.4955, 0.5085, 0.4890, 0.4833,
         0.4876, 0.4926, 0.4990, 0.4897, 0.4726, 0.5146, 0.4843, 0.4990, 0.4974,
         0.4808, 0.5122, 0.5399, 0.5172, 0.4935],
        [0.4673, 0.5045, 0.5344, 0.5262, 0.4840, 0.4839, 0.4896, 0.5186, 0.5215,
         0.4847, 0.5193, 0.4905, 0.5079, 0.5002, 0.4955, 0.5085, 0.4890, 0.4833,
         0.4876, 0.4926, 0.4990, 0.4897, 0.4726, 0.5146, 0.4843, 0.4990, 0.4974,
         0.4808, 0.5122, 0.5399, 0.5172, 0.4935]], grad_fn=<StackBackward0>)