In [1]:
import random
import torch.nn as nn
import numpy as np
import torch
import math

root = '../../'
bits = 16

In [2]:
def b():
    return [random.sample( [1,-1] , 1 )[0] for i in range( bits )]

b()

[-1, -1, 1, -1, -1, -1, -1, -1, 1, 1, -1, 1, -1, -1, -1, 1]

In [3]:
alpha = 3

a = torch.stack( [torch.tensor(b()) for i in range(5)] )
p = torch.stack( [torch.tensor(b()) for i in range(5)] )
n = torch.stack( [torch.tensor(b()) for i in range(5)] )

s = torch.nn.Sigmoid( )
neg = torch.sum(a * p, (1)) * 0.5
pos = torch.sum(a * n, (1)) * 0.5

val = pos - neg - alpha

seg1 = -torch.sum( -(val - torch.log(1 + math.e**val )) )

In [4]:
torch.stack( [torch.tensor(b()) for i in range(5)] )

tensor([[ 1, -1,  1,  1, -1,  1, -1, -1,  1,  1, -1,  1, -1, -1,  1,  1],
        [-1,  1, -1, -1,  1,  1,  1,  1, -1,  1,  1, -1, -1,  1, -1,  1],
        [ 1,  1,  1, -1, -1,  1,  1, -1,  1, -1, -1,  1,  1,  1, -1, -1],
        [ 1,  1,  1,  1,  1,  1,  1, -1, -1, -1, -1,  1,  1, -1,  1,  1],
        [ 1,  1,  1, -1, -1, -1,  1, -1,  1,  1,  1, -1, -1,  1, -1, -1]])

In [5]:
model = nn.Sequential(  nn.Linear(4096,256),
                        nn.ReLU(),
                        nn.Linear(256, bits),
                        )

In [6]:
X_train = torch.tensor( np.load( root + "Features/train_features_vgg16_cifar10.npy" ) )
y_train = np.load( root + "Features/train_labels_vgg16_cifar10.npy" )

X_test = torch.tensor( np.load( root + "Features/test_features_vgg16_cifar10.npy" ) )
y_test = np.load( root + "Features/test_labels_vgg16_cifar10.npy" )

In [7]:
torch.stack( [torch.tensor(b()) for i in range(5)] )

tensor([[-1, -1, -1, -1,  1, -1, -1, -1, -1, -1, -1, -1,  1, -1, -1, -1],
        [-1, -1,  1,  1, -1, -1, -1, -1, -1, -1,  1, -1, -1, -1,  1, -1],
        [ 1,  1,  1, -1,  1, -1, -1, -1, -1, -1,  1, -1, -1,  1,  1, -1],
        [ 1, -1,  1, -1,  1,  1,  1, -1, -1,  1,  1, -1, -1,  1,  1,  1],
        [-1,  1, -1, -1, -1,  1, -1,  1, -1,  1, -1, -1,  1,  1, -1,  1]])

In [8]:
len(X_train)

45000

In [9]:
torch.stack( [torch.tensor(b()) for i in range(5)] )

tensor([[-1, -1, -1, -1, -1,  1, -1, -1, -1,  1, -1,  1,  1,  1,  1,  1],
        [ 1,  1, -1,  1,  1,  1,  1,  1,  1,  1, -1, -1, -1, -1,  1, -1],
        [-1,  1, -1,  1, -1, -1,  1, -1, -1,  1,  1, -1, -1, -1, -1, -1],
        [-1,  1,  1, -1,  1, -1,  1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
        [-1,  1,  1, -1, -1, -1,  1,  1,  1,  1,  1, -1, -1,  1,  1, -1]])

In [10]:
#lambda_ = 4

#u = model(X_train)
#b = torch.sign( u )

#seg2 = lambda_ * torch.sum( torch.sqrt( torch.sum( (b - u)**2, (1)) ) )

#seg2

------------

In [11]:
torch.stack( [torch.tensor(b()) for i in range(5)] )

tensor([[ 1,  1, -1,  1,  1,  1, -1, -1, -1,  1,  1,  1, -1,  1,  1,  1],
        [ 1, -1, -1, -1, -1, -1, -1,  1, -1,  1,  1,  1, -1, -1, -1, -1],
        [ 1, -1,  1, -1,  1,  1,  1, -1, -1, -1, -1,  1,  1, -1, -1, -1],
        [ 1,  1,  1,  1,  1,  1, -1,  1,  1,  1, -1,  1, -1,  1, -1,  1],
        [ 1, -1, -1,  1,  1,  1,  1, -1,  1, -1, -1,  1, -1,  1,  1,  1]])

In [13]:
def loss(a,p,n, u):

    neg = torch.sum(a * p, (1)) * 0.5
    pos = torch.sum(a * n, (1)) * 0.5

    val = pos - neg - alpha

    seg1 = -torch.sum( -(val - torch.log(1 + math.e**val )) )

    lambda_ = 4

    b = torch.sign( u )

    seg2 = lambda_ * torch.sum( torch.sqrt( torch.sum( (b - u)**2, (1)) ) )

    return seg1 + seg2


a = torch.stack( [torch.tensor(b()) for i in range(5)] )
p = torch.stack( [torch.tensor(b()) for i in range(5)] )
n = torch.stack( [torch.tensor(b()) for i in range(5)] )

u = model(X_train)

loss(a, p, n, u)

tensor(547066.4375, grad_fn=<AddBackward0>)

In [58]:
from torch.utils.data import DataLoader

dataloader = DataLoader(list(range(100)), batch_size=20, shuffle=True)

for batch in dataloader:
    print(batch)

tensor([29, 89, 15, 41, 75, 74, 88, 52, 58, 97, 39, 79, 49, 96, 57, 90,  9, 24,
        53, 86])
tensor([ 0,  3, 77, 72,  7,  2,  5, 30, 23, 44, 83, 40, 67, 78,  1,  6, 76, 42,
        51, 31])
tensor([33, 46, 47, 95, 21, 19, 14, 25, 18, 37, 60, 73, 17, 43, 27, 34, 55, 81,
        93, 87])
tensor([56, 11, 66, 94, 32, 85, 61, 64, 84, 71, 99, 45, 82, 38, 70, 16, 62, 10,
        50, 92])
tensor([12, 69, 20,  4, 22, 91, 68, 35, 28, 80, 65, 63, 54, 48, 98, 13, 36, 26,
        59,  8])


In [78]:
# == LOAD IN THE DATA ==
X_train = torch.tensor( np.load( root + "Features/train_features_vgg16_cifar10.npy" ) )
y_train = np.load( root + "Features/train_labels_vgg16_cifar10.npy" )

# == MAKE DATA LOADER ==
train_data = []
for i in range(len(X_train)):
   train_data.append([X_train[i], y_train[i]])
dataloader = DataLoader(train_data, batch_size=100, shuffle=True)

# == LOOP THROUGH THE BATCHES ==
for batch in dataloader:
    X_batch = batch[0]
    y_batch = batch[1]

    

    break # ! REMOVE

In [79]:
y_batch

tensor([5, 4, 3, 2, 6, 8, 7, 9, 6, 2, 2, 8, 1, 4, 6, 0, 0, 9, 7, 3, 9, 7, 4, 2,
        9, 9, 3, 3, 5, 3, 3, 1, 5, 1, 0, 7, 6, 8, 4, 8, 2, 7, 0, 8, 6, 6, 4, 1,
        3, 0, 1, 7, 9, 0, 3, 0, 6, 7, 2, 2, 5, 3, 2, 4, 7, 8, 5, 7, 5, 3, 8, 7,
        0, 9, 5, 3, 7, 4, 3, 4, 6, 1, 0, 5, 0, 7, 8, 2, 8, 1, 9, 4, 5, 1, 9, 6,
        1, 4, 5, 9])

In [80]:
pn_dict = {}

for label in y_batch.unique():
    pn_dict[label] = {"n":[], "p":[]}
    
    
    for i, val in enumerate(y_batch):
        if (val == label):
            pn_dict[label]["p"].append(i)
        else:
            pn_dict[label]["n"].append(i)
    
    break
pn_dict

{tensor(0): {'n': [0,
   1,
   2,
   3,
   4,
   5,
   6,
   7,
   8,
   9,
   10,
   11,
   12,
   13,
   14,
   17,
   18,
   19,
   20,
   21,
   22,
   23,
   24,
   25,
   26,
   27,
   28,
   29,
   30,
   31,
   32,
   33,
   35,
   36,
   37,
   38,
   39,
   40,
   41,
   43,
   44,
   45,
   46,
   47,
   48,
   50,
   51,
   52,
   54,
   56,
   57,
   58,
   59,
   60,
   61,
   62,
   63,
   64,
   65,
   66,
   67,
   68,
   69,
   70,
   71,
   73,
   74,
   75,
   76,
   77,
   78,
   79,
   80,
   81,
   83,
   85,
   86,
   87,
   88,
   89,
   90,
   91,
   92,
   93,
   94,
   95,
   96,
   97,
   98,
   99],
  'p': [15, 16, 34, 42, 49, 53, 55, 72, 82, 84]}}

In [126]:
N = torch.stack([ X_batch[i_n] for i_n in pn_dict[list(pn_dict)[0]]["n"] ])
P = torch.stack([ X_batch[i_n] for i_n in pn_dict[list(pn_dict)[0]]["p"] ])

torch.matmul(P, N.transpose(1, 0))[1][1]

tensor(6444.4561)

In [123]:
print(N.shape)
print(P.shape)

torch.Size([90, 4096])
torch.Size([10, 4096])


In [116]:
P.transpose(1, 0).shape

torch.Size([4096, 10])

In [70]:
temp_L = ["A", "B", "C"]

for i, element in enumerate(temp_L):
    print(i, element)

0 A
1 B
2 C


In [ ]:
torch.stack([ X_batch[i_n] for i_n in pn_dict[list(pn_dict)[0]]["n"] ])

tensor([ 0.6582,  0.4635, -1.4231,  ..., -1.6680, -0.5448, -1.8827])