In [60]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torchvision.datasets import CIFAR10
import torchvision.transforms as transforms
from torch.utils.data import DataLoader, Subset, TensorDataset
import random
import numpy as np
from sklearn.decomposition import PCA
from typing import Tuple
from tqdm import tqdm
from scipy.spatial import distance_matrix
import pandas as pd

In [61]:
root = "/Users/kristiansjorslevnielsen/Documents/DVP7/"
# load data
X_train = torch.tensor( np.load(root + "Features/cifar10/train_features_vgg16_cifar10.npy" ) )
y_train = np.load(root + "Features/cifar10/train_labels_vgg16_cifar10.npy" )

X_test = torch.tensor( np.load(root + "Features/cifar10/test_features_vgg16_cifar10.npy" ) )
y_test = np.load(root + "Features/cifar10/test_labels_vgg16_cifar10.npy")

y_train_tensor = torch.tensor(y_train, dtype=torch.long)
y_test_tensor = torch.tensor(y_test, dtype=torch.long)

In [62]:
root = "/Users/kristiansjorslevnielsen/Documents/DVP7/"
# load data
X_train = torch.tensor( np.load(root + "Features/NusWidePCA/X_train_nus_wide.npy" ) )
y_train = np.load(root + "Features/NusWidePCA/y_train_nus_wide.npy" )

X_test = torch.tensor( np.load(root + "Features/NusWidePCA/X_test_nus_wide.npy" ) )
y_test = np.load(root + "Features/NusWidePCA/y_test_nus_wide.npy")

y_train_tensor = torch.tensor(y_train, dtype=torch.long)
y_test_tensor = torch.tensor(y_test, dtype=torch.long)

In [63]:
pca = PCA(n_components=128)
pca.fit(X_train)
#X_train = torch.tensor(pca.transform(X_train), dtype=torch.float)
#X_test = torch.tensor(pca.transform(X_test), dtype=torch.float)

PCA(n_components=128)

In [64]:
def meanAveragePrecision1(test_hashes, training_hashes, test_labels, training_labels):
    aps = []
    num_queries = len(test_hashes)
    for i in tqdm(range(num_queries)):
        label = test_labels[i]
        distances = (training_hashes != test_hashes[i]).sum(axis=1)  # Hamming distance
        tp = (training_labels == label)  # True positive indicator
        hash_df = pd.DataFrame({"distances": distances, "tp": tp.cpu().numpy()})
        hash_df = hash_df.sort_values(by="distances").reset_index(drop=True)
        hash_df["tp_cumsum"] = hash_df["tp"].cumsum()
        hash_df["precision"] = hash_df["tp_cumsum"] / (np.arange(len(hash_df)) + 1)
        ap = hash_df["precision"].where(hash_df["tp"] == 1).mean() if hash_df["tp"].sum() > 0 else 0
        aps.append(ap)

    return np.mean(aps)


In [65]:
def one_hot_encode(a):
    b = np.zeros((a.size, a.max() + 1))
    b[np.arange(a.size), a] = 1
    return b

In [66]:
def meanAveragePrecision(test_hashes, training_hashes, test_labels, training_labels):
    aps = []
    if len(training_labels.shape) == 1:
        training_labels = one_hot_encode(training_labels)
        test_labels = one_hot_encode(test_labels)
    for i, test_hash in enumerate(tqdm(test_hashes)):
        label = test_labels[i]
        distances = np.abs(training_hashes - test_hashes[i]).sum(axis=1)
        tp = np.where((training_labels*label).sum(axis=1)>0, 1, 0)
        hash_df = pd.DataFrame({"distances":distances, "tp":tp}).reset_index()
        hash_df = hash_df.sort_values(["distances", "index"]).reset_index(drop=True)
        hash_df = hash_df.drop(["index", "distances"], axis=1).reset_index()
        hash_df = hash_df[hash_df["tp"]==1]
        hash_df["tp"] = hash_df["tp"].cumsum()
        hash_df["index"] = hash_df["index"] +1 
        precision = np.array(hash_df["tp"]) / np.array(hash_df["index"])
        ap = precision.mean()
        aps.append(ap)
    
    return np.array(aps).mean()

In [67]:
a = 1
b = np.array([[1,0,1],[1,2,2]])
np.where((b*a).sum(axis=1)>0, 1, 0)

array([1, 1])

In [68]:
len(b.shape)

2

In [69]:
import torch
import torch.nn as nn
import torch.nn.functional as F

class SUBIC_encoder(nn.Module): 
    def __init__(self, input_size=4096, bits=48, num_classes=10, num_blocks=8, block_size=8):
        super(SUBIC_encoder, self).__init__()
       
        assert bits % num_blocks == 0, "Bits must be divisible by num_blocks"

        self.input_size = input_size
        self.bits = bits 
        self.num_blocks = num_blocks
        self.block_size = block_size
        

        # Define the encoder structure
        self.encoder = nn.Sequential(
            nn.Linear(input_size, 256), 
            nn.ReLU(),
            nn.Linear(256, bits)
        )  # Outputs binary feature vectors
        
        self.fc3 = nn.Linear(bits, num_classes)  # Logits for num_classes
    
    def block_softmax(self, x):
        
        batch_size = x.shape[0]
        block_size = x.shape[1] // self.num_blocks
        
        # Ensure that x has the expected shape
        assert x.shape[1] == self.bits, f"Expected shape [batch_size, {self.bits}], got {x.shape}"
        
        # Reshape and apply softmax
        x = x.view(batch_size, self.num_blocks, block_size)
        x = F.softmax(x, dim=-1) 
        return x.view(batch_size, -1) #-1 refers to the value that will match the original elements 
    
    def block_one_hot(self, x):
        batch_size = x.shape[0]

        x = x.view(batch_size, self.num_blocks, self.block_size)
        max_indices = x.argmax(dim=-1, keepdim=True)
        
        # Create one-hot encoding
        one_hot = torch.zeros_like(x).scatter_(-1, max_indices, 1)

        return one_hot.view(batch_size, self.bits)
    
    def forward(self, x, use_one_hot=False):
        # Ensure x is a flat tensor before passing to encoder
        batch_size = x.shape[0]
        x = x.view(batch_size, -1)  # Flatten if necessary

        z = self.encoder(x)

        if use_one_hot:
            binary_codes = self.block_one_hot(z)
        else:
            binary_codes = self.block_softmax(z)

        class_probs = F.softmax(self.fc3(binary_codes), dim=-1) 

        return class_probs, binary_codes


In [70]:
a = torch.tensor([[0.1,0.2,0.3,0.4],[0.4,0.3,0.2,0.1]])
b = torch.tensor([[1,0,1,0],[1,0,0,0]])
(a*b).sum(axis=1)

tensor([0.4000, 0.4000])

In [71]:
def entropy(p):
    entropy_result = -torch.sum(p * torch.log2(p + 1e-30), dim=-1)
    return entropy_result

def cross_entropy(class_prob, target):
    if len(target.shape) >1:
        s = (class_prob*target).sum(axis=1)
    else:
        s = class_prob[torch.arange(len(target)), target]
    return -torch.log2(s)/torch.log2(torch.FloatTensor([class_prob.shape[1]]))

def compute_total_loss(class_probs, target, binary_codes, num_blocks, block_size, gamma=0.5, mu=0.5):
    """
    Computes the total loss, which includes:
    - Cross-entropy classification loss
    - Mean entropy loss (encouraging one-hot encoding within each block)
    - Batch entropy loss (encouraging uniform distribution across blocks)
    
    Parameters:
    - class_probs: The class probabilities from the classification layer.
    - target: The true labels.
    - binary_codes: The binary codes generated by the encoder.
    - num_blocks: The number of blocks in the binary codes.
    - block_size: The size of each block in the binary codes.
    - gamma: Weight for the mean entropy loss.
    - mu: Weight for the batch entropy loss.
    
    """



    classification_loss = cross_entropy(class_probs, target)

    batch_size = binary_codes.shape[0]
    binary_codes = binary_codes.view(batch_size, num_blocks, block_size) #used in structure encoding



    #Mean Entropy Loss (encourages each block to resemble a one-hot vector) using softmax binary code
    mean_entropy_loss = entropy(binary_codes).mean(dim=1)

    #Batch Entropy Loss (encourages uniform distribution across blocks)
    average_support = binary_codes.mean(dim=0)  
    batch_entropy_loss = entropy(average_support).mean(dim=0)

    #Combine losses with weights gamma and mu
    entropy_loss = (gamma * mean_entropy_loss - mu * batch_entropy_loss)/torch.log2(torch.FloatTensor([block_size]))
    total_loss = (classification_loss + entropy_loss).mean()
    
    
    return total_loss

#logits, binary_codes = model(X_train, use_one_hot=False)
#loss = compute_total_loss(logits, y_train_tensor, binary_codes, num_blocks=8, block_size=4, gamma=0.5, mu=0.05)

In [72]:
model = SUBIC_encoder(bits = 48, input_size=X_train.shape[1], num_classes = y_train.shape[1], num_blocks = 16, block_size = 3)
optimizer = optim.Adam(model.parameters(), lr=0.001)
class_probs, binary_codes = model.forward(X_train, use_one_hot=False)

In [73]:
epochs = 100

train_dataset = TensorDataset(X_train, y_train_tensor)
train_loader = DataLoader(train_dataset, batch_size=64, shuffle=True)
test_dataset = TensorDataset(X_test, y_test_tensor)
test_loader = DataLoader(test_dataset, batch_size=64, shuffle=True)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
losses = []

for epoch in range(epochs):
    model.train()
    total_loss = 0.0

    for images, labels in train_loader:
        
        images, labels = images.to(device), labels.to(device)
        class_probs, binary_codes = model.forward(images, use_one_hot=False)


        # Compute loss and update model
        loss = compute_total_loss(class_probs, labels, binary_codes, num_blocks=16, block_size=3, gamma=0.5, mu=0.5)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        total_loss += loss.item()
    losses.append(total_loss / len(train_loader))
    print(f"Epoch [{epoch+1}/{epochs}], Loss: {total_loss / len(train_loader):.4f}")


Epoch [1/100], Loss: -0.2429
Epoch [2/100], Loss: -0.2945
Epoch [3/100], Loss: -0.3014
Epoch [4/100], Loss: -0.3051
Epoch [5/100], Loss: -0.3078
Epoch [6/100], Loss: -0.3099
Epoch [7/100], Loss: -0.3114
Epoch [8/100], Loss: -0.3128
Epoch [9/100], Loss: -0.3134
Epoch [10/100], Loss: -0.3147
Epoch [11/100], Loss: -0.3153
Epoch [12/100], Loss: -0.3156
Epoch [13/100], Loss: -0.3174
Epoch [14/100], Loss: -0.3178
Epoch [15/100], Loss: -0.3182
Epoch [16/100], Loss: -0.3181
Epoch [17/100], Loss: -0.3184
Epoch [18/100], Loss: -0.3184
Epoch [19/100], Loss: -0.3194
Epoch [20/100], Loss: -0.3202
Epoch [21/100], Loss: -0.3200
Epoch [22/100], Loss: -0.3197
Epoch [23/100], Loss: -0.3200
Epoch [24/100], Loss: -0.3209
Epoch [25/100], Loss: -0.3213
Epoch [26/100], Loss: -0.3217
Epoch [27/100], Loss: -0.3223
Epoch [28/100], Loss: -0.3223
Epoch [29/100], Loss: -0.3228
Epoch [30/100], Loss: -0.3221
Epoch [31/100], Loss: -0.3222
Epoch [32/100], Loss: -0.3232
Epoch [33/100], Loss: -0.3239
Epoch [34/100], Los

In [74]:
class_probs, hash = model.forward(X_test, use_one_hot=False)

In [75]:
class_probs[0]

tensor([2.9099e-01, 6.7566e-02, 7.9759e-04, 6.1973e-01, 2.8599e-04, 6.8810e-05,
        2.5979e-03, 4.3536e-04, 1.7497e-04, 6.4542e-03, 4.9198e-03, 4.9061e-04,
        2.3096e-05, 1.2931e-04, 2.3389e-03, 7.4246e-04, 7.0607e-04, 1.2520e-04,
        1.4536e-05, 1.4139e-03, 3.0372e-06], grad_fn=<SelectBackward0>)

In [76]:
_, train_binary_codes = model(X_train, use_one_hot=True)
_, test_binary_codes = model(X_test, use_one_hot=True)

train_binary_codes = train_binary_codes.detach().numpy()
test_binary_codes = test_binary_codes.detach().numpy()
test_binary_codes[9000:,].shape

(0, 48)

In [82]:
_, train_binary_codes = model(X_train, use_one_hot=True)
_, test_binary_codes = model(X_test, use_one_hot=True)

train_binary_codes = train_binary_codes.detach().numpy()
test_binary_codes = test_binary_codes.detach().numpy()

database = test_binary_codes[:2000,]
database_label = y_test[:2000,]
query_set = test_binary_codes[2000:,]
query_set_label = y_test[2000:,]


meanAveragePrecision(query_set, database, query_set_label, database_label)

100%|██████████| 100/100 [00:00<00:00, 961.34it/s]


0.782694631119518

In [81]:
database_label.shape

(2100, 21)

In [78]:
model.eval()
all_query_codes, all_query_labels = [], []
all_db_codes, all_db_labels = [], []

with torch.no_grad():
    for images, labels in test_loader:
        images, labels = images.to(device), labels.to(device)

        _, binary_codes = model(images, use_one_hot=True)

        # Ensure binary_codes is a tensor
        if not isinstance(binary_codes, torch.Tensor):
            raise TypeError("Expected binary_codes to be a tensor.")
        
        all_db_codes.append(binary_codes)
        all_db_labels.append(labels)

        if len(all_query_codes) == 0:  
            all_query_codes.append(binary_codes.clone())  
            all_query_labels.append(labels.clone())

# Concatenate all tensors
all_query_codes = torch.cat(all_query_codes, dim=0)
all_query_labels = torch.cat(all_query_labels, dim=0)
all_db_codes = torch.cat(all_db_codes, dim=0)
all_db_labels = torch.cat(all_db_labels, dim=0)

# Calculate MAP Score
map_score = meanAveragePrecision(
    all_query_codes,
    all_db_codes,
    all_query_labels,
    all_db_labels
    )

print(f"MAP Score: {map_score:.5f}")

100%|██████████| 64/64 [00:00<00:00, 643.42it/s]

MAP Score: 0.74599
